### ISSUE TITLE
Resource does not set

### ISSUE THREAD

**Issue by daniel-yavorovich** [maxpowel/jQuery-XMPP-plugin#1]
Hello!

I have problem with using 'resource' parametr.
I have been used for this settings:

<pre><code>
$.xmpp.connect({jid:"{{ jabber_id }}", password:"{{ jabber_pass }}", resource:"{{ first_name }}_{{ last_name }}", url:"{{ http_bind }}",
                onDisconnect:function() {
                    $.xmpp.setPresence("offline");
                },
                onConnect: function() {
                    document.getElementById("messages_block").innerHTML = "<b>{{ first_name }} {{ last_name }}</b>, Вы вошли в чат. Пожалуйста, опишите свой вопрос.<br>";
                    $.xmpp.setPresence(null);
                },
                onIq: function(iq){
                    console.log("onIq");
                },
                onMessage: function(message){
                addElement("touser", "<b>Admin</b>: " + message.body);
                },
                onPresence: function(presence){
                console.log("New presence of " + presence.from + " is " + presence.show);
                }
            });
</code></pre>

But messages from JS-client delivered from resource "undefined".

I'm doing something wrong, or is it a bug in the code?

Thanks.

---

Best regards,
Daniel Yavorovich

P.S.
Sorry for my lousy English.

**Comment by maxpowel** [comment]
Hi!

Thank you for the problem notification ;)
There was a bug in the code but now I think that it is fixed.
Also, now you can provide the resource parameter when you send the message (useful for support multiple conversations with different resources). If no resource is provided when you send a message, the global resource (provided on connection) will be used (if any)

Please confirm if your problem is really fixed o not.

Thank you!

**Comment by daniel-yavorovich** [comment]
Hello!

Ability to identify a resource is working fine.

Thank you for the quick solution!

**Comment by maxpowel** [comment]
Thanks, and if you find any problem o need something in the library please request it ;)
