### ISSUE TITLE
How to get Roster?

### ISSUE THREAD

**Issue by zenwong** [maxpowel/jQuery-XMPP-plugin#4]
is there anyway to get the roster?

using sendCommand? but I'm not sure what I need to put in rawCommand.

**Comment by maxpowel** [comment]
Hi! When you connect to your xmpp server, the server should send you the roster. It is caught and sent to onPresence event, one event per user in the roster. But it is only optional (as is said here http://xmpp.org/rfcs/rfc3921.html#intro-requirements) so I will add a way to do an excplicity roster request. I will notice when this feature is ready, hope today

**Comment by maxpowel** [comment]
I have just pushed this feature.
Once you are connected the roster can be fetched like this:
$.xmpp.getRoster(function(roster){
//process roster
});

The callback function will recibe an array containing the roster. Every entry of this array is an object with the values name, subscription an jid. You can see the basic-connection.html example to see how it works.

If your problem is solved, please close the issue.
Thanks!

**Comment by zenwong** [comment]
It's working, thanks dude

**Comment by ghost** [comment]
The getRoster callback is never called, but I received the iq response through onIq.

I am using ejabberd 2.1.2-2ubuntu0.1 as xmpp server.

**Comment by ghost** [comment]
Hi,
I am getting this error message "TypeError $.xmpp is undefined" in firefox and, 
"Uncaught TypeError: Cannot call method 'connect' of undefined" in chrome.

It was working fine but suddenly i am seeing this messages
