### ISSUE TITLE
xmpp plugin and nginx

### ISSUE THREAD

**Issue by mrsum** [maxpowel/jQuery-XMPP-plugin#8]
JabberClient does not reconnect when network connectivity connection to the server is lost.

**Comment by maxpowel** [comment]
Ok, thanks for the notice. I'm working on fix it

**Comment by maxpowel** [comment]
Hi! Sorry for late!
Now when the connection is lost the event onDisconnect and onError is triggered.
The default time to detect it is 60 seconds, but you can set this time using the parameter "wait" when you use the method "connect".

$.xmpp.connect({url:url, wait: 10, jid: jid, password: password ...

As the protocol is HTTP the way to detect a network failure is if the server does not respond in X seconds. Because of that, the network failure can't be detected instantly. More details here http://xmpp.org/extensions/xep-0124.html/

It works for you?

**Comment by bluemoz** [comment]
Perfect! Thanks

**Comment by bluemoz** [comment]
Could you complete your last example with a reconnect feature example?
Thanks for your great job

**Comment by maxpowel** [comment]
Hi! sorry for late. Please try something like this:

onError: function(){
    if($.xmpp.connected == false){
          //reconnect
   }
}

It's not the better solution but it works. I'm thinking on a better error management
